import os

import gvsoc.systree
import gvsoc.runner

import vp.clock_domain
import pulp.floonoc_flex.floonoc_flex
import interco.traffic.generator
from memory.memory import Memory

import driver

# 2x2x2 3D-mesh flexible FlooNoc, generated by gen_topology.py (run
# beforehand with `make topology`, see the tutorial's Makefile) into
# generated/mesh3d.{floogen,routing,link_latencies}.yml. The Z axis was
# generated with a much higher per-link latency than X/Y, to show that the
# flexible model, unlike the fixed 2D-mesh FlooNoc from the previous
# section, takes its whole topology (including per-link timing) from data
# instead of from a hardcoded shape.
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
TOPOLOGY_DIR = os.path.join(_THIS_DIR, 'generated')
TOPOLOGY_NAME = 'mesh3d'

DIM_X = 2
DIM_Y = 2
DIM_Z = 2

MEM_BASE = 0x9000_0000
MEM_SIZE = 0x10_0000

# The cluster whose network interface plays the role of a shared memory
# target: every other cluster's generator sends its dummy traffic there,
# so half of them have to cross the slow Z-axis link to reach it.
TARGET_CLUSTER = (0, 0, 0)


def _ni_name(x, y, z):
    return f'cluster_{x}_{y}_{z}_ni'


class Soc(gvsoc.systree.Component):
    def __init__(self, parent: gvsoc.systree.Component, name: str):
        super().__init__(parent, name)

        noc = pulp.floonoc_flex.floonoc_flex.FlooNocFlex(
            self, 'noc', narrow_width=8, wide_width=8, ni_outstanding_reqs=32,
            router_input_queue_size=2,
            network_path=os.path.join(TOPOLOGY_DIR, f'{TOPOLOGY_NAME}.floogen.yml'),
            routing_path=os.path.join(TOPOLOGY_DIR, f'{TOPOLOGY_NAME}.routing.yml'),
            default_link_latency=1,
            link_latencies_path=os.path.join(TOPOLOGY_DIR, f'{TOPOLOGY_NAME}.link_latencies.yml'))

        target_node_id = noc.id_map[_ni_name(*TARGET_CLUSTER)]
        mem = Memory(self, 'mem', size=MEM_SIZE)
        noc.o_NARROW_MAP(mem.i_INPUT(), MEM_BASE, MEM_SIZE, target_node_id, rm_base=True)

        clusters = [(x, y, z)
            for z in range(DIM_Z) for y in range(DIM_Y) for x in range(DIM_X)
            if (x, y, z) != TARGET_CLUSTER]

        drv = driver.Driver(self, 'driver', nb_generators=len(clusters),
            target_base=MEM_BASE, transfer_size=4096, packet_size=64)

        for index, (x, y, z) in enumerate(clusters):
            node_id = noc.id_map[_ni_name(x, y, z)]
            generator = interco.traffic.generator.Generator(self, f'generator_{x}_{y}_{z}')
            generator.o_OUTPUT(noc.i_NARROW_INPUT(node_id))
            drv.o_GENERATOR(index, generator.i_CONTROL())


# Wraps the SoC with its clock generator, like a normal gvsoc chip
class Chip(gvsoc.systree.Component):
    def __init__(self, parent: gvsoc.systree.Component, name: str=None):
        super().__init__(parent, name)

        clock = vp.clock_domain.Clock_domain(self, 'clock', frequency=100000000)
        soc = Soc(self, 'soc')
        clock.o_CLOCK(soc.i_CLOCK())


# This is the top target that gapy will instantiate
class Target(gvsoc.runner.Target):
    gapy_description = "Flexible FlooNoc 3D mesh with a variable-latency Z axis"
    model = Chip
    name = "my_system"
