#!/usr/bin/env python3
"""
Renders a 3D mesh topology generated by gen_topology.py, coloring each link
by its latency (read from <name>.link_latencies.yml). This is the plot that
makes the variable-latency Z axis visible at a glance: X/Y links are drawn
thin, Z links thick and color-scaled by their (larger) latency.

Usage:
    python3 plot_latency.py --dir generated --name mesh3d --out mesh3d.png
"""

import argparse
import re

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import cm
import yaml


_ROUTER_RE = re.compile(r'^router_(\d+)_(\d+)_(\d+)$')


def _coords(name):
    m = _ROUTER_RE.match(name)
    if not m:
        return None
    return tuple(int(v) for v in m.groups())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dir', default='generated')
    parser.add_argument('--name', default='mesh3d')
    parser.add_argument('--out', default=None, help='PNG path (default: <dir>/<name>.png)')
    args = parser.parse_args()

    latencies_path = f'{args.dir}/{args.name}.link_latencies.yml'
    with open(latencies_path) as f:
        link_latencies = yaml.safe_load(f)

    # Only router-to-router links describe the mesh geometry: NI<->router
    # "spoke" links are dropped for clarity.
    edges = []
    for src, dsts in link_latencies.items():
        src_xyz = _coords(src)
        if src_xyz is None:
            continue
        for dst, latency in dsts.items():
            dst_xyz = _coords(dst)
            if dst_xyz is None:
                continue
            edges.append((src_xyz, dst_xyz, latency))

    all_latencies = [latency for _, _, latency in edges]
    lat_min, lat_max = min(all_latencies), max(all_latencies)

    fig = plt.figure(figsize=(7, 6))
    ax = fig.add_subplot(projection='3d')

    cmap = matplotlib.colormaps['viridis']

    def color_for(latency):
        if lat_max == lat_min:
            return cmap(0.5)
        return cmap((latency - lat_min) / (lat_max - lat_min))

    for (x0, y0, z0), (x1, y1, z1), latency in edges:
        is_z_link = z0 != z1
        ax.plot([x0, x1], [y0, y1], [z0, z1],
            color=color_for(latency),
            linewidth=4 if is_z_link else 1.5,
            solid_capstyle='round')

    routers = {(x, y, z) for (x, y, z), _, _ in edges} | {xyz for _, xyz, _ in edges}
    xs, ys, zs = zip(*routers)
    ax.scatter(xs, ys, zs, color='black', s=40, depthshade=False)

    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    ax.set_title(f'{args.name}: link latency (thick = Z axis)')

    mappable = cm.ScalarMappable(cmap=cmap)
    mappable.set_array(all_latencies)
    fig.colorbar(mappable, ax=ax, shrink=0.6, label='latency (cycles)')

    out = args.out or f'{args.dir}/{args.name}.png'
    fig.savefig(out, dpi=150, bbox_inches='tight')
    print(f'Wrote "{out}"')


if __name__ == '__main__':
    main()
