router_0_0:
  cluster_ni_0_0: cluster_ni_0_0
  cluster_ni_1_0: router_1_0
  cluster_ni_2_0: router_1_0
  cluster_ni_3_0: router_1_0
  cluster_ni_0_1: router_0_1
  cluster_ni_1_1: router_1_0
  cluster_ni_2_1: router_1_0
  cluster_ni_3_1: router_1_0
  cluster_ni_0_2: router_0_1
  cluster_ni_1_2: router_1_0
  cluster_ni_2_2: router_1_0
  cluster_ni_3_2: router_1_0
  cluster_ni_0_3: router_0_1
  cluster_ni_1_3: router_1_0
  cluster_ni_2_3: router_1_0
  cluster_ni_3_3: router_1_0
router_1_0:
  cluster_ni_0_0: router_0_0
  cluster_ni_1_0: cluster_ni_1_0
  cluster_ni_2_0: router_2_0
  cluster_ni_3_0: router_2_0
  cluster_ni_0_1: router_0_0
  cluster_ni_1_1: router_1_1
  cluster_ni_2_1: router_2_0
  cluster_ni_3_1: router_2_0
  cluster_ni_0_2: router_0_0
  cluster_ni_1_2: router_1_1
  cluster_ni_2_2: router_2_0
  cluster_ni_3_2: router_2_0
  cluster_ni_0_3: router_0_0
  cluster_ni_1_3: router_1_1
  cluster_ni_2_3: router_2_0
  cluster_ni_3_3: router_2_0
router_2_0:
  cluster_ni_0_0: router_1_0
  cluster_ni_1_0: router_1_0
  cluster_ni_2_0: cluster_ni_2_0
  cluster_ni_3_0: router_3_0
  cluster_ni_0_1: router_1_0
  cluster_ni_1_1: router_1_0
  cluster_ni_2_1: router_2_1
  cluster_ni_3_1: router_3_0
  cluster_ni_0_2: router_1_0
  cluster_ni_1_2: router_1_0
  cluster_ni_2_2: router_2_1
  cluster_ni_3_2: router_3_0
  cluster_ni_0_3: router_1_0
  cluster_ni_1_3: router_1_0
  cluster_ni_2_3: router_2_1
  cluster_ni_3_3: router_3_0
router_3_0:
  cluster_ni_0_0: router_2_0
  cluster_ni_1_0: router_2_0
  cluster_ni_2_0: router_2_0
  cluster_ni_3_0: cluster_ni_3_0
  cluster_ni_0_1: router_2_0
  cluster_ni_1_1: router_2_0
  cluster_ni_2_1: router_2_0
  cluster_ni_3_1: router_3_1
  cluster_ni_0_2: router_2_0
  cluster_ni_1_2: router_2_0
  cluster_ni_2_2: router_2_0
  cluster_ni_3_2: router_3_1
  cluster_ni_0_3: router_2_0
  cluster_ni_1_3: router_2_0
  cluster_ni_2_3: router_2_0
  cluster_ni_3_3: router_3_1
router_0_1:
  cluster_ni_0_0: router_0_0
  cluster_ni_1_0: router_1_1
  cluster_ni_2_0: router_1_1
  cluster_ni_3_0: router_1_1
  cluster_ni_0_1: cluster_ni_0_1
  cluster_ni_1_1: router_1_1
  cluster_ni_2_1: router_1_1
  cluster_ni_3_1: router_1_1
  cluster_ni_0_2: router_0_2
  cluster_ni_1_2: router_1_1
  cluster_ni_2_2: router_1_1
  cluster_ni_3_2: router_1_1
  cluster_ni_0_3: router_0_2
  cluster_ni_1_3: router_1_1
  cluster_ni_2_3: router_1_1
  cluster_ni_3_3: router_1_1
router_1_1:
  cluster_ni_0_0: router_0_1
  cluster_ni_1_0: router_1_0
  cluster_ni_2_0: router_2_1
  cluster_ni_3_0: router_2_1
  cluster_ni_0_1: router_0_1
  cluster_ni_1_1: cluster_ni_1_1
  cluster_ni_2_1: router_2_1
  cluster_ni_3_1: router_2_1
  cluster_ni_0_2: router_0_1
  cluster_ni_1_2: router_1_2
  cluster_ni_2_2: router_2_1
  cluster_ni_3_2: router_2_1
  cluster_ni_0_3: router_0_1
  cluster_ni_1_3: router_1_2
  cluster_ni_2_3: router_2_1
  cluster_ni_3_3: router_2_1
router_2_1:
  cluster_ni_0_0: router_1_1
  cluster_ni_1_0: router_1_1
  cluster_ni_2_0: router_2_0
  cluster_ni_3_0: router_3_1
  cluster_ni_0_1: router_1_1
  cluster_ni_1_1: router_1_1
  cluster_ni_2_1: cluster_ni_2_1
  cluster_ni_3_1: router_3_1
  cluster_ni_0_2: router_1_1
  cluster_ni_1_2: router_1_1
  cluster_ni_2_2: router_2_2
  cluster_ni_3_2: router_3_1
  cluster_ni_0_3: router_1_1
  cluster_ni_1_3: router_1_1
  cluster_ni_2_3: router_2_2
  cluster_ni_3_3: router_3_1
router_3_1:
  cluster_ni_0_0: router_2_1
  cluster_ni_1_0: router_2_1
  cluster_ni_2_0: router_2_1
  cluster_ni_3_0: router_3_0
  cluster_ni_0_1: router_2_1
  cluster_ni_1_1: router_2_1
  cluster_ni_2_1: router_2_1
  cluster_ni_3_1: cluster_ni_3_1
  cluster_ni_0_2: router_2_1
  cluster_ni_1_2: router_2_1
  cluster_ni_2_2: router_2_1
  cluster_ni_3_2: router_3_2
  cluster_ni_0_3: router_2_1
  cluster_ni_1_3: router_2_1
  cluster_ni_2_3: router_2_1
  cluster_ni_3_3: router_3_2
router_0_2:
  cluster_ni_0_0: router_0_1
  cluster_ni_1_0: router_1_2
  cluster_ni_2_0: router_1_2
  cluster_ni_3_0: router_1_2
  cluster_ni_0_1: router_0_1
  cluster_ni_1_1: router_1_2
  cluster_ni_2_1: router_1_2
  cluster_ni_3_1: router_1_2
  cluster_ni_0_2: cluster_ni_0_2
  cluster_ni_1_2: router_1_2
  cluster_ni_2_2: router_1_2
  cluster_ni_3_2: router_1_2
  cluster_ni_0_3: router_0_3
  cluster_ni_1_3: router_1_2
  cluster_ni_2_3: router_1_2
  cluster_ni_3_3: router_1_2
router_1_2:
  cluster_ni_0_0: router_0_2
  cluster_ni_1_0: router_1_1
  cluster_ni_2_0: router_2_2
  cluster_ni_3_0: router_2_2
  cluster_ni_0_1: router_0_2
  cluster_ni_1_1: router_1_1
  cluster_ni_2_1: router_2_2
  cluster_ni_3_1: router_2_2
  cluster_ni_0_2: router_0_2
  cluster_ni_1_2: cluster_ni_1_2
  cluster_ni_2_2: router_2_2
  cluster_ni_3_2: router_2_2
  cluster_ni_0_3: router_0_2
  cluster_ni_1_3: router_1_3
  cluster_ni_2_3: router_2_2
  cluster_ni_3_3: router_2_2
router_2_2:
  cluster_ni_0_0: router_1_2
  cluster_ni_1_0: router_1_2
  cluster_ni_2_0: router_2_1
  cluster_ni_3_0: router_3_2
  cluster_ni_0_1: router_1_2
  cluster_ni_1_1: router_1_2
  cluster_ni_2_1: router_2_1
  cluster_ni_3_1: router_3_2
  cluster_ni_0_2: router_1_2
  cluster_ni_1_2: router_1_2
  cluster_ni_2_2: cluster_ni_2_2
  cluster_ni_3_2: router_3_2
  cluster_ni_0_3: router_1_2
  cluster_ni_1_3: router_1_2
  cluster_ni_2_3: router_2_3
  cluster_ni_3_3: router_3_2
router_3_2:
  cluster_ni_0_0: router_2_2
  cluster_ni_1_0: router_2_2
  cluster_ni_2_0: router_2_2
  cluster_ni_3_0: router_3_1
  cluster_ni_0_1: router_2_2
  cluster_ni_1_1: router_2_2
  cluster_ni_2_1: router_2_2
  cluster_ni_3_1: router_3_1
  cluster_ni_0_2: router_2_2
  cluster_ni_1_2: router_2_2
  cluster_ni_2_2: router_2_2
  cluster_ni_3_2: cluster_ni_3_2
  cluster_ni_0_3: router_2_2
  cluster_ni_1_3: router_2_2
  cluster_ni_2_3: router_2_2
  cluster_ni_3_3: router_3_3
router_0_3:
  cluster_ni_0_0: router_0_2
  cluster_ni_1_0: router_1_3
  cluster_ni_2_0: router_1_3
  cluster_ni_3_0: router_1_3
  cluster_ni_0_1: router_0_2
  cluster_ni_1_1: router_1_3
  cluster_ni_2_1: router_1_3
  cluster_ni_3_1: router_1_3
  cluster_ni_0_2: router_0_2
  cluster_ni_1_2: router_1_3
  cluster_ni_2_2: router_1_3
  cluster_ni_3_2: router_1_3
  cluster_ni_0_3: cluster_ni_0_3
  cluster_ni_1_3: router_1_3
  cluster_ni_2_3: router_1_3
  cluster_ni_3_3: router_1_3
router_1_3:
  cluster_ni_0_0: router_0_3
  cluster_ni_1_0: router_1_2
  cluster_ni_2_0: router_2_3
  cluster_ni_3_0: router_2_3
  cluster_ni_0_1: router_0_3
  cluster_ni_1_1: router_1_2
  cluster_ni_2_1: router_2_3
  cluster_ni_3_1: router_2_3
  cluster_ni_0_2: router_0_3
  cluster_ni_1_2: router_1_2
  cluster_ni_2_2: router_2_3
  cluster_ni_3_2: router_2_3
  cluster_ni_0_3: router_0_3
  cluster_ni_1_3: cluster_ni_1_3
  cluster_ni_2_3: router_2_3
  cluster_ni_3_3: router_2_3
router_2_3:
  cluster_ni_0_0: router_1_3
  cluster_ni_1_0: router_1_3
  cluster_ni_2_0: router_2_2
  cluster_ni_3_0: router_3_3
  cluster_ni_0_1: router_1_3
  cluster_ni_1_1: router_1_3
  cluster_ni_2_1: router_2_2
  cluster_ni_3_1: router_3_3
  cluster_ni_0_2: router_1_3
  cluster_ni_1_2: router_1_3
  cluster_ni_2_2: router_2_2
  cluster_ni_3_2: router_3_3
  cluster_ni_0_3: router_1_3
  cluster_ni_1_3: router_1_3
  cluster_ni_2_3: cluster_ni_2_3
  cluster_ni_3_3: router_3_3
router_3_3:
  cluster_ni_0_0: router_2_3
  cluster_ni_1_0: router_2_3
  cluster_ni_2_0: router_2_3
  cluster_ni_3_0: router_3_2
  cluster_ni_0_1: router_2_3
  cluster_ni_1_1: router_2_3
  cluster_ni_2_1: router_2_3
  cluster_ni_3_1: router_3_2
  cluster_ni_0_2: router_2_3
  cluster_ni_1_2: router_2_3
  cluster_ni_2_2: router_2_3
  cluster_ni_3_2: router_3_2
  cluster_ni_0_3: router_2_3
  cluster_ni_1_3: router_2_3
  cluster_ni_2_3: router_2_3
  cluster_ni_3_3: cluster_ni_3_3