import os
import re

import gvsoc.systree
import gvsoc.runner

import vp.clock_domain
import pulp.floonoc_flex.floonoc_flex
import interco.traffic.generator
from memory.memory import Memory

import driver

# 3D-mesh flexible FlooNoc, generated by gen_topology.py (run beforehand with
# `make topology`, see the tutorial's Makefile) into
# generated/mesh3d.{floogen,routing,link_latencies}.yml. The Z axis is
# typically generated with a much higher per-link latency than X/Y, to show
# that the flexible model, unlike the fixed 2D-mesh FlooNoc from the
# previous section, takes its whole topology (including per-link timing)
# from data instead of from a hardcoded shape.
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
TOPOLOGY_DIR = os.path.join(_THIS_DIR, 'generated')
TOPOLOGY_NAME = 'mesh3d'

MEM_BASE = 0x9000_0000
TILE_MEM_SIZE = 0x10_0000

TRANSFER_SIZE = 4096 * 64
PACKET_SIZE = 64

_ROUTER_RE = re.compile(r'^router_(\d+)_(\d+)_(\d+)$')


def _mesh_dims(id_map):
    """Derives (dim_x, dim_y, dim_z) from the router node names FlooNocFlex
    parsed out of the generated topology, instead of hardcoding them."""
    coords = [tuple(int(v) for v in m.groups())
        for m in (_ROUTER_RE.match(name) for name in id_map) if m]
    xs, ys, zs = zip(*coords)
    return max(xs) + 1, max(ys) + 1, max(zs) + 1


def _ni_name(x, y, z):
    return f'cluster_{x}_{y}_{z}_ni'


def _mirror(dims, x, y, z):
    dim_x, dim_y, dim_z = dims
    return (dim_x - 1 - x, dim_y - 1 - y, dim_z - 1 - z)


def _tile_base(dims, x, y, z):
    dim_x, dim_y, _ = dims
    tile_id = (z * dim_y + y) * dim_x + x
    return MEM_BASE + tile_id * TILE_MEM_SIZE


class Soc(gvsoc.systree.Component):
    def __init__(self, parent: gvsoc.systree.Component, name: str):
        super().__init__(parent, name)

        noc = pulp.floonoc_flex.floonoc_flex.FlooNocFlex(
            self, 'noc', narrow_width=8, wide_width=8, ni_outstanding_reqs=32,
            router_input_queue_size=2,
            network_path=os.path.join(TOPOLOGY_DIR, f'{TOPOLOGY_NAME}.floogen.yml'),
            routing_path=os.path.join(TOPOLOGY_DIR, f'{TOPOLOGY_NAME}.routing.yml'),
            default_link_latency=1,
            link_latencies_path=os.path.join(TOPOLOGY_DIR, f'{TOPOLOGY_NAME}.link_latencies.yml'))

        dims = _mesh_dims(noc.id_map)
        dim_x, dim_y, dim_z = dims
        clusters = [(x, y, z)
            for z in range(dim_z) for y in range(dim_y) for x in range(dim_x)]

        # One local memory per cluster, mapped directly onto that cluster's
        # own NoC node.
        for (x, y, z) in clusters:
            node_id = noc.id_map[_ni_name(x, y, z)]
            mem = Memory(self, f'mem_{x}_{y}_{z}', size=TILE_MEM_SIZE)
            noc.o_NARROW_MAP(mem.i_INPUT(), _tile_base(dims, x, y, z), TILE_MEM_SIZE, node_id, rm_base=True)

        # Each generator's target is its mirror tile's memory address.
        targets = [_tile_base(dims, *_mirror(dims, x, y, z)) for (x, y, z) in clusters]

        drv = driver.Driver(self, 'driver', targets=targets, transfer_size=TRANSFER_SIZE, packet_size=PACKET_SIZE)

        for index, (x, y, z) in enumerate(clusters):
            node_id = noc.id_map[_ni_name(x, y, z)]
            generator = interco.traffic.generator.Generator(self, f'generator_{x}_{y}_{z}')
            generator.o_OUTPUT(noc.i_NARROW_INPUT(node_id))
            drv.o_GENERATOR(index, generator.i_CONTROL())


# Wraps the SoC with its clock generator, like a normal gvsoc chip
class Chip(gvsoc.systree.Component):
    def __init__(self, parent: gvsoc.systree.Component, name: str=None):
        super().__init__(parent, name)

        clock = vp.clock_domain.Clock_domain(self, 'clock', frequency=100000000)
        soc = Soc(self, 'soc')
        clock.o_CLOCK(soc.i_CLOCK())


# This is the top target that gapy will instantiate
class Target(gvsoc.runner.Target):
    gapy_description = "Flexible FlooNoc 3D mesh with a variable-latency Z axis"
    model = Chip
    name = "my_system"
